### ISSUE TITLE
[COMP]: Add layout utilities, via CSS Modules

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/component-library#98]
Even just a CSS file that gets added — I think it will be useful to have Sass helpers like `@include full-absolute(4px)` (yes I'm aware of inset 😛 )

**Comment by andrewrubin** [comment]
Some utilities I often find helpful are below. Should these be included in some kind of utility class stylesheet, or would we rather implement that on a per-project basis? 

Let me know your thoughts @marlonmarcello @rvno @NicholasLancey !

```scss
.block {
  display: block;
}

.relative {
  position: relative;
}

.fill {
  width: 100%;
}

.constrain {
  max-width: 100%;
}

.center {
  margin-inline: auto;
}
```
